# Funding configuration for Rook Protocol

github: rook-protocol

# Other funding methods can be added:
# open_collective: rook-protocol
# ko_fi: rookprotocol
# custom: ['https://rook-protocol.xyz/donate']
